#ESTE ARCHIVO NO LO ESTOY USANDO YA Q NO APLIQUÉ VARIABLES DE AMBIENTE AL PROYECTO.
apiVersion: v1
kind: ConfigMap
metadata:
  name: usuarios
data:
  port: "8001"
  db_host: "mysql8:3306"
  database: msvc_usuarios
  username: root
  password: sasa
  curso_url: "msvc-cursos:8002"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cursos
data:
  port: "8002"
  db_host: "postgres14:5432"
  database: msvc_cursos
  username: postgres
  password: sasa
  curso_url: "msvc-usuarios:8001"