version: "3.9"
services:
  
  mysql8:
    container_name: c_mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring    
  
  postgres14:
    container_name: c_postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data 
    restart: always
    networks:
      - spring
      
  usuarios:
    container_name: c_usuarios
    image: 4xe1/usuarios                                                          #CLASE 98 AHORA TOMA LA IMAGEN DESDE EL DOCKER HUB.
#   image: usuarios                                                               #ESTE SE USA CUANDO LAS IMAGENES YA ESTÁN CONSTRUIDAS DESDE ANTES.
#   build:                                                                    #PARA CONSTRUIR LAS IMAGENES AUTOMÁTICAMENTE SI ES QUE NO ESTÁN CONSTRUIDAS. TOMA LA IMAGEN DEL PC
#     context: ./                                                                  #PUNTO DE PARTIDA DESDE DONDE SE VAN A COPIAR LOS ARCHIVOS.
#     dockerfile: ./usuarios/Dockerfile                                            #DONDE ESTÁ EL DOCKERFILE.
    ports:
      - "8001:8001"
    #env_file: ./usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always
    
  cursos:
    container_name: c_cursos
    image: 4xe1/cursos                                                       #CLASE 98 AHORA TOMA LA IMAGEN DESDE EL DOCKER HUB.
#   image: cursos                                                            #CON ESTE SE ACCEDE A LA IMAGEN CURSOS QUE SE TIENEN EN EL PC.
#   build:                                                                   #COMENTADO EN CLASE 98
#     context: ./                                                            #COMENTADO EN CLASE 98
#     dockerfile: ./cursos/Dockerfile                                        #COMENTADO EN CLASE 98
    ports:
      - "8002:8002"
    #env_file: ./cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - usuarios
    restart: always
  
#SE DEFINEN REDES y VOLUMENES PARA EL COMPOSE
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
  
networks:
  spring:
    name: spring
  
  
